# Generated by Django 4.0.4 on 2022-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('exampleEmail', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=10000)),
                ('Phone', models.CharField(max_length=50)),
                ('text_area', models.CharField(max_length=2000000)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
