# Generated by Django 4.0.4 on 2022-05-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_text_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='exampleEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='text_area',
            new_name='message',
        ),
    ]
