# Generated by Django 4.0.4 on 2022-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=models.TextField(verbose_name='#id_content'),
        ),
    ]
