# Generated by Django 4.0.4 on 2022-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=models.TextField(),
        ),
    ]
