# Generated by Django 4.0.4 on 2022-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contant',
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(default='', max_length=25015),
        ),
        migrations.AlterField(
            model_name='post',
            name='TimeStamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
