# Generated by Django 4.0.4 on 2022-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_content_post_contant_post_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='athour',
            field=models.CharField(max_length=1003),
        ),
    ]
