# Generated by Django 4.0.4 on 2022-06-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_post_athour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='TimeStamp',
            field=models.DateField(null=True),
        ),
    ]
