# Generated by Django 4.0.4 on 2022-06-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_post_timestamp_alter_post_athour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='athour',
            field=models.CharField(max_length=1023),
        ),
    ]
