# Generated by Django 4.0.4 on 2022-06-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_post_athour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contant',
            new_name='content',
        ),
    ]
