# Generated by Django 4.0.4 on 2022-06-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_content_post_contant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contant',
            new_name='content',
        ),
    ]
