# Generated by Django 4.0.4 on 2022-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_job_content_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_responsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='Requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.TextField(),
        ),
    ]
