# Generated by Django 4.0.4 on 2022-06-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_job_experience_alter_job_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Timestamp',
        ),
    ]
