# Generated by Django 4.0.4 on 2022-06-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_message_contact_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Website',
            new_name='Website_URL',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
    ]
