# Generated by Django 4.0.4 on 2022-06-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_website_contact_website_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=10000)),
                ('City', models.CharField(max_length=10000)),
                ('State', models.CharField(max_length=10000)),
                ('Education', models.CharField(max_length=10000)),
                ('Experience', models.CharField(max_length=12122)),
                ('LinkedIn', models.CharField(max_length=12122)),
                ('GitHub', models.CharField(max_length=12122)),
                ('About', models.TextField()),
                ('Skills', models.TextField()),
                ('myfile', models.FileField(upload_to='')),
            ],
        ),
    ]
