# Generated by Django 4.0.4 on 2022-06-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_jobapply_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='myfile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
