# Generated by Django 4.0.4 on 2022-06-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_jobapply_myfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapply',
            old_name='myfile',
            new_name='file',
        ),
    ]
